### ISSUE TITLE
electron 调用报错

### ISSUE THREAD

**Issue by CQBoyBrand** [kejiacheng/kscreenshot#16]
我是在ready里面调用的 

ReferenceError: window is not defined
      at Object.<anonymous> (/Users/brand/work/code/client/node_modules/kscreenshot/dist/kss.js:1:359)
      at Object.<anonymous> (/Users/brand/work/code/client/node_modules/kscreenshot/dist/kss.js:3:3)
      at Module._compile (module.js:642:30)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/brand/work/code/client/dist/electron/main.js:7441:18)

**Comment by kejiacheng** [comment]
你是怎么调用的

**Comment by kejiacheng** [comment]
你在调用我这个插件前一行，打印一下window看一下吧。

**Comment by CQBoyBrand** [comment]
我在electron的ready方法中调用的，没有window这个东西。你这里面的window是指electron创建的窗体吗
重庆崽儿Brand
brandhuang@qq.com

**Comment by kejiacheng** [comment]
不会吧，electron没有window？

**Comment by kejiacheng** [comment]
我这里的window指的是全局window对象

**Comment by CQBoyBrand** [comment]
我不放在主进程里面试下看看。。
重庆崽儿Brand
brandhuang@qq.com

**Comment by CQBoyBrand** [comment]
你在electron里面是是什么时候初始化这个插件的？

**Comment by kejiacheng** [comment]
我只在nw里面使用过。
初始化readme有写，这个不管在web,还是electron,nw都是一样的

**Comment by wangbinglu08** [comment]
在electron的使用有结果了吗？我也是在electron下面使用提示window找不到。

**Comment by kejiacheng** [comment]
这个得你自己看下electron为什么没有window

**Comment by CQBoyBrand** [comment]
> 在electron的使用有结果了吗？我也是在electron下面使用提示window找不到。

我项目目前木没有使用这个了 。。。暂时用的另一个，只是单纯的截图功能

**Comment by gouxiwen** [comment]
electron里有global全局对象，没有window对象，这样的化electron应用无法使用这儿插件了

**Comment by gouxiwen** [comment]
electron里有global全局对象，没有window对象，能不能优化一下兼容global对象  @kejiacheng

**Comment by kejiacheng** [comment]
> electron里有global全局对象，没有window对象，能不能优化一下兼容global对象 @kejiacheng

我这边周末的时候，使用electron看下。目前周间没时间调试。

**Comment by kejiacheng** [comment]
> electron里有global全局对象，没有window对象，能不能优化一下兼容global对象 @kejiacheng

我这里大致调了一下，你们用electron的时候，不要在创建浏览器窗口的js文件里面引用kscreenshot。你这个js文件是属于node，肯定是没有浏览器当中的这些全局对象，所以你们正确的做法是在前端范畴的js文件当中引用kscreenshot。
